import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLinkedin, faGithub } from "../public/icon/pro-brands-svg-icons";

import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";

const inter = Space_Mono({ subsets: ["latin"], weight: "700" });

export const metadata: Metadata = {
  title: "Mahdi Khoramjoo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className} suppressHydrationWarning={true}>
        {children}
        <section className='fixed w-full h-20 bottom-0 left-0 flex justify-center items-center gap-4 backdrop-blur-sm'>
          <FontAwesomeIcon className='bg-white' icon={faLinkedin} size='3x' />
          <FontAwesomeIcon className='bg-white' icon={faGithub} size='3x' />
        </section>
      </body>
    </html>
  );
}
